### ISSUE TITLE
Relative width of GridColumns not working

### ISSUE THREAD

**Issue by MattMarked** [xamarin/MobileBlazorBindings#43] opened 2020-01-16 16:07 UTC
It seems it doesn't compute the relative width, with gridunittype.star , correctly.

Example of code

```xml
  <Grid>
            <Layout>
                <ColumnDefinition GridUnitType="GridUnitType.Star" Width="1" ></ColumnDefinition>
                <ColumnDefinition GridUnitType="GridUnitType.Star" Width="3" ></ColumnDefinition>
            </Layout>
            <Contents>
                @foreach (var tipper in tippersManager.Tippers)
                {
                    <TipperRow tipper="tipper" row="rowCount"></TipperRow>
                    rowCount++;
                }
            </Contents>
        </Grid>
```

And the component TipperRow:

```xml
<GridCell Row="@row" Column="0">
    <Image Source="ImgSource" BackgroundColor="Color.Black"  HorizontalOptions="LayoutOptions.Start" VerticalOptions="LayoutOptions.Center" WidthRequest="1"/>
</GridCell>
<GridCell Row="@row" Column="1">
    <Label Text="@tipper.Name" HorizontalOptions="LayoutOptions.Start" FontSize="25"  VerticalOptions="LayoutOptions.Center"
           FontAttributes="FontAttributes.Bold" />
</GridCell>
```

as you can see, I would expect, in each row of the grid, an image with Width 1/4 of the total width of the row, (or 1/3 of the label width).

But it seems each gridcell take up to 50% of the available space.

**Comment by Eilon** [comment] 2020-01-16 18:57
This certainly seems unexpected, so we will investigate. Thank you for checking out Mobile Blazor Bindings and sharing your thoughts!

**Comment by Eilon** [comment] 2020-08-03 23:32
I finally tried to reproduce this and I'm not seeing any problem. Of course, it's 1/2 a year later, so who knows what changed since then 😄 

Here's what I used:

Tipper class:

```c#
    public class Tipper
    {
        public string Name { get; set; }
    }
```

Main page:

```xml
<ContentView>
    <Grid ColumnDefinitions="1*, 3*">
        @{
            var rowCount = 0;
        }
        @foreach (var tipper in tippers)
        {
            <TipperRow tipper="tipper" row="rowCount"></TipperRow>
            rowCount++;
        }
    </Grid>

</ContentView>

@code
{
    List<Tipper> tippers = new List<Tipper>
{
        new Tipper {Name="First Tipper" },
        new Tipper {Name="Second Tipper" },
        new Tipper {Name="Third Tipper" },
    };
}
```

TipperRow:

```xml
<GridCell Row="@row" Column="0">
    <Image Source="@ImageSource" BackgroundColor="Color.Purple" HorizontalOptions="LayoutOptions.Start" VerticalOptions="LayoutOptions.Center" />
</GridCell>
<GridCell Row="@row" Column="1">
    <Label Text="@tipper.Name" HorizontalOptions="LayoutOptions.Start" FontSize="25" VerticalOptions="LayoutOptions.Center"
           FontAttributes="FontAttributes.Bold" BackgroundColor="Color.Orange" />
</GridCell>

@code
{
    [Parameter] public int row { get; set; }
    [Parameter] public Tipper tipper { get; set; }

    string ImageSource = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Twemoji_1f527.svg/60px-Twemoji_1f527.svg.png";

    int count;

    void IncrementCount()
    {
        count++;
    }
}
```

The only thing that I thought was odd is that the original code shown had `WidthRequest="1"` on the image, which means it'll render as 1 pixel wide in its container (so it's just a line or a dot). But the cell it's in is still appearing as 25% of the width for me. Other than that I also changed the background colors of the controls so that they would show up more clearly (purple and orange).

Here it is _without_ `WidthRequest="1"`, you can see 25% width image cell, 75% width text cell (though the controls themselves don't take up the whole cell):

![image](https://user-images.githubusercontent.com/202643/89236801-62f91580-d5a6-11ea-9037-1b889fab3be0.png)

And this is _with_ `WidthRequest="1"`, you can see 25% width image cell, 75% width text cell, and the image is only 1x1 pixel so it's just a tiny purple square:

![image](https://user-images.githubusercontent.com/202643/89236899-b10e1900-d5a6-11ea-912b-96872b1143e6.png)

**Comment by Eilon** [comment] 2020-08-03 23:35
Now, if you want the images and labels to be much larger, you can set all their layout options to be `LayoutOptions.FillAndExpand` (or whatever else suits you). With this TipperRow:

```xml
<GridCell Row="@row" Column="0">
    <Image Source="@ImageSource" BackgroundColor="Color.Purple" HorizontalOptions="LayoutOptions.FillAndExpand" VerticalOptions="LayoutOptions.FillAndExpand" />
</GridCell>
<GridCell Row="@row" Column="1">
    <Label Text="@tipper.Name" HorizontalOptions="LayoutOptions.FillAndExpand" FontSize="25" VerticalOptions="LayoutOptions.FillAndExpand"
           FontAttributes="FontAttributes.Bold" BackgroundColor="Color.Orange" />
</GridCell>
```

I get this lovely layout:

![image](https://user-images.githubusercontent.com/202643/89237185-617c1d00-d5a7-11ea-930e-c784d39a0efa.png)

**Comment by Eilon** [comment] 2020-08-03 23:36
And here are the full docs on various layout options: https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/layouts/layout-options

Anyway, if there was a bug here, it seems fixed by now. If you're still running into an issue, please let me know and I will investigate more. Thank you for the report!

**Closed by Eilon** 2020-08-03 23:36 UTC
Labels: area-mobileblazorbindings
