### ISSUE TITLE
TodoSample Exception: Page must not already have a parent

### ISSUE THREAD

**Issue by Alby-o** [xamarin/MobileBlazorBindings#90] opened 2020-02-26 01:00 UTC
To reproduce:
1. Run the TodoSample 
2. Create a todo
3. Double click on the "..." to open the TodoEntryDetails

![Page must not already have a parent](https://user-images.githubusercontent.com/29965798/75301621-0707c380-5887-11ea-91f0-d2a0e72c0478.gif)

**Comment by Eilon** [comment] 2020-03-03 05:46
Hmm oh yuck! I was quite certain I had this working a few days ago. This is of course not supposed to happen so I will investigate. My apologies!

**Comment by Eilon** [comment] 2020-03-11 20:18
I've tried several times to reproduce this on the latest code base and I'm not seeing this error.

Were you running this from the repo? Or did you use the sample source code with the packages from NuGet.org? Or something else?

In the meantime I'm closing this because it could be that there was an issue at some point but it was fixed. I'll re-open the issue if there's additional info that shows there is still a bug. Thank you!

**Closed by Eilon** 2020-03-11 20:18 UTC
