### ISSUE TITLE
Build error on template

### ISSUE THREAD

**Issue by Kahbazi** [xamarin/MobileBlazorBindings#70] opened 2020-01-30 11:40 UTC
I get this error when trying to build the new template Android project.

Can not resolve reference: `Microsoft.Bcl.AsyncInterfaces`, referenced by `System.Text.Json`. Please add a NuGet package or assembly reference for `Microsoft.Bcl.AsyncInterfaces`, or remove the reference to `System.Text.Json`.	FirstMobileBlazorBindingsApp.Android			

Can not resolve reference: `System.Diagnostics.EventLog`, referenced by `Microsoft.Extensions.Logging.EventLog`. Please add a NuGet package or assembly reference for `System.Diagnostics.EventLog`, or remove the reference to `Microsoft.Extensions.Logging.EventLog`.	FirstMobileBlazorBindingsApp.Android

**Comment by Eilon** [comment] 2020-01-30 17:24
Hi @Kahbazi sorry you ran into this problem. Can you tell me more about your environment and how you tried to build the project? Are you on Windows or Mac? Which Visual Studio? And did you try to build from command line or from within VS?

**Comment by Kahbazi** [comment] 2020-02-01 06:47
I'm trying to build within Visual Studio on Windows.

Visual Studio 16.4.3
Xamarin   16.4.000.308 (d16-4@4755fb3)
Xamarin Designer   16.4.0.475 (remotes/origin/d16-4@ac250f5aa)
Xamarin Templates   16.4.25 (579ee62)
Xamarin.Android SDK   10.1.3.7 (d16-4/d66aed0)
Xamarin.iOS and Xamarin.Mac SDK   13.10.0.17 (5f802ef)

This is the result of dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Eilon** [comment] 2020-02-02 05:01
Hi @Kahbazi thank you for the additional info, I will take a closer look. On the surface I would have expected it to work, so I'll think about it some more and try to figure out what's going on.

**Comment by Kahbazi** [comment] 2020-02-02 06:49
@Eilon I opened Visual Studio as administrator and the Android project built successfully, but I still get the same error when running Visual Studio with non-admin user.

**Comment by Eilon** [comment] 2020-02-06 23:22
Hi @Kahbazi I've asked some colleagues and this issue does not seem familiar to anyone.

So you ran the `dotnet new` command from the command line, then opened the SLN in VS, and when you try to build, you get this error? Are there any other steps?

**Comment by Kahbazi** [comment] 2020-02-07 09:37
Thanks @Eilon. Yes this is exactly what I'm doing. There are no more steps.
Feel free to close this issue since I am able to build with Visual Studio running as Administrator.
Nevertheless I am curios on why I can't build the project with normal user.

**Comment by kant2002** [comment] 2020-02-12 08:30
@Eilon what steps needed for troubleshoot this issue? I have exact same issue. This is similar to https://github.com/xamarin/xamarin-android/issues/4074 or https://github.com/xamarin/xamarin-android/issues/4182 and I actually have similar issue with Generic Host in Xamarin see https://github.com/dotnet/extensions/issues/1631

I willing to do debugging, but need some guidance in which places to start looking first.

**Comment by kant2002** [comment] 2020-02-12 08:31
@Kahbazi does by a chance you have `NUGET_PACKAGES` env variable set?

**Comment by Kahbazi** [comment] 2020-02-12 08:56
@kant2002 yes I have nuget in environment variable for my user. This is probably the issue since I have no problem when I switch to another account.
So I think this issue has nothing to do with this project. Perhaps the issue is with how nuget works or Xamarin itself. @Eilon where should we transfer this issue?

**Comment by kant2002** [comment] 2020-02-25 10:04
@Eilon I check that xamarin#4171 somewhat fix the issue. It is fixed it for me, but PR is not fully completed. so maybe not work for all. One caveat is that I manually build the Xamarin from sources.

**Comment by Eilon** [comment] 2020-07-22 21:05
Hi folks, sorry for the large delay on this.

I agree this issue doesn't seem specific to Mobile Blazor Bindings because the projects it generates are all common types of .NET projects used in Visual Studio.

I also agree that it makes sense to find a better place to log this issue, but without being able to reproduce it myself to investigate, I recommend trying to find or log a new bug in one of these locations:

1. Xamarin.Forms: https://github.com/xamarin/Xamarin.Forms
1. Xamarin Android: https://github.com/xamarin/xamarin-android
1. NuGet: https://github.com/NuGet/Home
1. .NET Core: https://github.com/dotnet/sdk

As such, I'm closing the issue here because there is no further action planned as part of Mobile Blazor Bindings.

**Closed by Eilon** 2020-07-22 21:05 UTC
