### ISSUE TITLE
IJSRuntime injection as web-specific service 

### ISSUE THREAD

**Issue by soags** [xamarin/MobileBlazorBindings#150] opened 2020-07-25 09:36 UTC
I think IJSRuntime is needed as a default web-specific service for hybrid-application.  
IJSRuntime is required when developers implement JS interop or use Blazor UI Liblary.

```C#
@inject IJSRuntime JSRuntime;
```
```C#
[Inject]
protected IJSRuntime Js { get; set; }
```

Blazor WebAssembly have a function to inject DefaultWebAssemblyJSRuntime into IJSRuntime.  
```C#
namespace Microsoft.AspNetCore.Components.WebAssembly.Hosting
{
    public sealed class WebAssemblyHostBuilder
    {
        internal void InitializeDefaultServices()
        {
            Services.AddSingleton<IJSRuntime>(DefaultWebAssemblyJSRuntime.Instance);
            Services.AddSingleton<NavigationManager>(WebAssemblyNavigationManager.Instance);
            Services.AddSingleton<INavigationInterception>(WebAssemblyNavigationInterception.Instance);
            Services.AddSingleton(new LazyAssemblyLoader(DefaultWebAssemblyJSRuntime.Instance));
            Services.AddLogging(builder => {
                builder.AddProvider(new WebAssemblyConsoleLoggerProvider(DefaultWebAssemblyJSRuntime.Instance));
            });
        }
    }
}
```

For example, I think adding IJSRuntime settings to the AddBlazorHybrid method is a good idea.
But, I can't get an instance of DefaultWebAssemblyJSRuntime.
So I'm not sure if it's a good idea to use DefaultWebAssemblyJSRuntime.

```C#
namespace Microsoft.Extensions.DependencyInjection
{
    public static class BlazorHybridServiceCollectionExtensions
    {
        public static void AddBlazorHybrid(this IServiceCollection services)
        {            
            services.AddScoped<NavigationManager, BlazorHybridNavigationManager>();
            services.AddScoped<INavigationInterception, BlazorHybridNavigationInterception>();
            services.AddScoped<IJSRuntime>(DefaultWebAssemblyJSRuntime.Instance);
        }
    }
}
```

- Do you think need IJSRuntime injection ?
- If yes, does DefaultWebAssemblyJSRuntime is correct for inject  IJSRuntime ? BlazorHybridJSRuntime ?
- If yes, any idea ?

Thanks in advance.

**Comment by Eilon** [comment] 2020-07-27 18:14
Hi @soags , this is a very interesting question. Can you share more details on why you think it is needed? I'm only a bit familiar with this part of Blazor but if you can share more details, I can consult with some people who are the true experts on this.

**Comment by soags** [comment] 2020-07-28 04:54
Hi @Eilon .
Thank you for your great work. (I forgot to write this last time)  
I'm not a seasoned Xamarin/Blazor developer, so I'm sorry if I say something wrong.  
I want to share my thoughts.

## Problem
1. Follow the first steps in [Microsoft's Blazor JS interop documents](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1).   
(using HybridAppSample/HybridApp and HybridApp.Windows project.)
Sample project is [here](https://github.com/soags/MobileBlazorBindings/tree/sample-%23150)
2. An error occurs when loading the screen and the screen does not appear.
```
Cannot provide a value for property 'JSRuntime' on type 'HybridApp.WebUI.Pages.Index'. There is no registered service of type 'Microsoft.JSInterop.IJSRuntime'.
```
This error does not print to the console when using MobileBlazorBindings as a DLL. By referring MobileBlazorBindings as a project, the following error can be confirmed.

A similar error occurs when using a third party library (e.g. MatBlazor) that uses DI of IJSRuntime.

StackTrace
```
'HybridApp.Windows.exe' (CoreCLR: clrhost): 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.5\System.Reflection.Metadata.dll' が読み込まれました。シンボルの読み込みをスキップしました。モジュールは最適化されていて、デバッグ オプションの [マイ コードのみ] 設定が有効になっています。
'HybridApp.Windows.exe' (CoreCLR: clrhost): 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.5\System.Collections.Immutable.dll' が読み込まれました。シンボルの読み込みをスキップしました。モジュールは最適化されていて、デバッグ オプションの [マイ コードのみ] 設定が有効になっています。
System.InvalidOperationException: Cannot provide a value for property 'JSRuntime' on type 'HybridApp.WebUI.Pages.Index'. There is no registered service of type 'Microsoft.JSInterop.IJSRuntime'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass5_0.<CreateInitializer>g__Initialize|2(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

## Investigation

You can bypass the error and appear screen by creating a TestJSRuntime class and adding it to web-specific services.  Therefore, I think that MobileBlazorBindings use web-specific services to resolve IJSRuntime injection. Currently web-specific services are not contained IJSRuntime, so injector can not do it.

Many Blazor projects are using JS-interop on the premise that will be  injected IJSRuntime.
Because, Blazor WebAssembly have a DefaultWebAssemblyJSRuntime as default IJSRuntime. 

```C#
public class TestJSRuntime : IJSRuntime
{
    public ValueTask<TValue> InvokeAsync<TValue>(string identifier, object[] args)
    {
        throw new System.NotImplementedException();
    }

    public ValueTask<TValue> InvokeAsync<TValue>(string identifier, CancellationToken cancellationToken, object[] args)
    {
        throw new System.NotImplementedException();
    }
}
```

```C#
public App()
{
    BlazorHybridHost.AddResourceAssembly(GetType().Assembly, contentRoot: "WebUI/wwwroot");

    var host = MobileBlazorBindingsHost.CreateDefaultBuilder()
        .ConfigureServices((hostContext, services) =>
        {
            // Adds web-specific services such as NavigationManager
            services.AddBlazorHybrid();
            services.AddScoped<IJSRuntime, TestJSRuntime>();

            // Register app-specific services
            services.AddSingleton<CounterState>();
        })
        .Build();

    MainPage = new ContentPage { Title = "My Application" };
    host.AddComponent<Main>(parent: MainPage);
}
```

I think that setting the "correct" JSRuntime class will solve the problem.  But I'm not sure what the "correct" JSRuntime class is.

In case of Blazor WebAssembly project, DefaultWebAssemblyJSRuntime is used for IJSRuntime, but DefaultWebAssemblyJSRuntime is internal scoped. Therefore, it has not been verified.

And I'm not sure what BlazorHybridJSRuntime is doing. If this can be .NET/JS-interop as IJSRuntime then this may be fine.

## Conclusion
- If a developer or third party library uses IJSRuntime injection, Web-specific services are used for injection.
- Currently, web-specific services do not include the definition of IJSRuntime, so injecting IJSRuntime gives an error.

**Comment by soags** [comment] 2020-07-28 08:43
I found the solution.
It seems that it can be solved by adding BlazorHybridJSRuntime to ServiceCollection.
See this [commit](https://github.com/soags/MobileBlazorBindings/commit/7abd02fe816869daee9f3915c2923c8b4199e18e).

Initialization of BlazorHybridJSRuntime is delayed using Proxy.
Because, creation of BlazorHybridJSRuntime is after the creation of ServiceProvider.
If there is a method that does not use singleton, I think it is better.

Will be able to use JSinterop, and Blazor UI libraries (e.g.MatBlazor).
And I think most existing Blazor WebAssembly projects will work as-is.

**Comment by Eilon** [comment] 2020-07-28 17:04
Hi @soags thanks for sharing all this info. I'll have a chat with some more Blazor experts to understand what the right solution is here.

**Comment by ktaze1** [comment] 2020-09-25 18:41
Is there an update with the JSRuntime so far?

For instance I've tried to fix anchor links in the webview since they don't work properly by using JsInterop but JSRuntime still doesn't work. 

For the time being I don't really _have to_ use anchor links but I think JS Interop is kinda essential. 

> I found the solution.
> It seems that it can be solved by adding BlazorHybridJSRuntime to ServiceCollection.
> See this [commit](https://github.com/soags/MobileBlazorBindings/commit/7abd02fe816869daee9f3915c2923c8b4199e18e).

Should we proceed with this approach?


--------------------

Here is what I tried to fix achorlinks if someone wanna check. Unfortunately any usage of IJSRuntime gives a blank page. 

AnchorLink.razor: (This component will replace `<a>`)
```
@code {

    public AnchorLink()
    {
        this.Attributes = new Dictionary<string, object>();
    }

    private string targetId = null;
    private bool preventDefault = false;

    [Parameter(CaptureUnmatchedValues = true)]
    public IDictionary<string, object> Attributes { get; set; }

    [Parameter]
    public RenderFragment ChildContent { get; set; }

    [Inject]
    protected IJSRuntime JsInterop { get; set; }  // Problematic


    protected override void OnParametersSet()
    {
        string href = null;
        if (this.Attributes.ContainsKey("href"))
        {
            href = $"{this.Attributes["href"]}";
            if (href.StartsWith("#"))
            {
                // If the href contains an anchor link we don't want the default click action to occur, but
                // rather take care of the click in our own method.
                this.targetId = href.Substring(1);
                this.preventDefault = true;
            }
        }
        base.OnParametersSet();
    }

    private async Task AnchorOnClickAsync()
    {
        if (!string.IsNullOrEmpty(this.targetId))
        {
            await this.JsInterop.InvokeVoidAsync("anchorLink.scrollIntoView", this.targetId);
        }
    }

}

<a @attributes="this.Attributes" @onclick="this.AnchorOnClickAsync" @onclick:preventDefault="@this.preventDefault">@this.ChildContent</a>
```

Js File: (will be included in index.html)
```
window.anchorLink = {
    scrollIntoView: function (elementId) {
        // This function is called from the AnchorLink component using JavaScript interop.
        // It will try to find an element using the ID given to the function, and scroll that
        // element into view, if an element is found.
        var elem = document.getElementById(elementId);
        if (elem) {
            elem.scrollIntoView();
            window.location.hash = elementId;
        }
    }
}
```

**Comment by arivera12** [comment] 2020-09-26 03:03
I can bet easily that over 90% of blazor libraries uses the IJSRuntime hardly o at some point. This should come in baked in `services.AddBlazorHybrid()`.

**Comment by arivera12** [comment] 2020-09-26 21:40
I am unavailable to port an existing application cause it's dependant on IJSRuntime.

**Comment by arivera12** [comment] 2020-09-26 22:48
> I found the solution.
> It seems that it can be solved by adding BlazorHybridJSRuntime to ServiceCollection.
> See this [commit](https://github.com/soags/MobileBlazorBindings/commit/7abd02fe816869daee9f3915c2923c8b4199e18e).
> 
> Initialization of BlazorHybridJSRuntime is delayed using Proxy.
> Because, creation of BlazorHybridJSRuntime is after the creation of ServiceProvider.
> If there is a method that does not use singleton, I think it is better.
> 
> Will be able to use JSinterop, and Blazor UI libraries (e.g.MatBlazor).
> And I think most existing Blazor WebAssembly projects will work as-is.

@soags so u make IJSRuntime run with the changes on that commit you added?

**Comment by arivera12** [comment] 2020-09-28 19:01
@Eilon when this gonna be added?

**Comment by Eilon** [comment] 2020-09-29 17:37
Sorry I haven't taken a close look at this yet. It does sound useful so this is still on the TODO list.

**Comment by arivera12** [comment] 2020-09-29 17:41
> Sorry I haven't taken a close look at this yet. It does sound useful so this is still on the TODO list.

This is vital on blazor apps, once this its added we can migrate all blazor apps into this without any headaches and should work as-is.

**Comment by Eilon** [comment] 2020-09-29 17:49
@arivera12 were you able to use any workaround mentioned earlier to see if it will work for you?

**Comment by arivera12** [comment] 2020-09-30 00:22
@Eilon I will give it a try to this https://github.com/soags/MobileBlazorBindings/commit/7abd02fe816869daee9f3915c2923c8b4199e18e!

**Comment by arivera12** [comment] 2020-09-30 18:58
@Eilon I am unavailable to compile this project. 

![image](https://user-images.githubusercontent.com/5600102/94727851-4de1fe00-032d-11eb-97c2-547df60fa89e.png)

I execute dotnet restore but says that all package are all up to date. 

Am I missing something like a development dependency or something else?

**Comment by Eilon** [comment] 2020-09-30 20:39
Hi @arivera12 I'm not sure if you can use `dotnet restore` and `dotnet build` for these projects. I believe you need to open a Visual Studio Developer Command Prompt (it should be in your Start Menu) and run `msbuild /t:restore` and then `msbuild /t:build` to restore and build the project.

Or if you can share more info about what error(s) you're getting I will investigate further.

**Comment by arivera12** [comment] 2020-09-30 20:40
Ok I give it a ty right now.

**Comment by arivera12** [comment] 2020-09-30 20:44
It seems I am missing the nodejs stuff. I am installing it.

**Comment by Eilon** [comment] 2020-09-30 21:58
Ah, yes, nodejs is required to compile the JS/TypeScript code!

**Comment by arivera12** [comment] 2020-09-30 22:08
> Ah, yes, nodejs is required to compile the JS/TypeScript code!

OMW, internet is slow here :(

**Comment by arivera12** [comment] 2020-10-01 19:19
I compiled successfully everything but **HybridApp.Windows** is not working properly. 

The **BlazorWebView** isn't not displaying anything.

![image](https://user-images.githubusercontent.com/5600102/94853254-20628680-03f9-11eb-8a24-6dca2f59f1e8.png)

Also when I press the increment button this exception get's thrown.

![image](https://user-images.githubusercontent.com/5600102/94853356-4be57100-03f9-11eb-9f14-272780298c3d.png)

I downloaded the **Master** branch and haven't applied any changes yet since I wanted to see it run first by default.

Am I missing something?

**Comment by arivera12** [comment] 2020-10-01 19:39
I tried `HybridApp.Android` and worked properly the default project

![MicrosoftTeams-image](https://user-images.githubusercontent.com/5600102/94855226-2efe6d00-03fc-11eb-8a59-3c5edd0b96cf.png)

I will apply JsRuntime code and try again over android device.

**Comment by arivera12** [comment] 2020-10-01 20:02
JsRuntime worked properly with @soags changes to the source code!

![image](https://user-images.githubusercontent.com/5600102/94857146-075cd400-03ff-11eb-8387-2b25cc61d1a0.png)

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/5600102/94857454-8520df80-03ff-11eb-8fe0-ed49e03e93d0.png)

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/5600102/94857459-86520c80-03ff-11eb-98f2-33f9be6f2649.png)

**Comment by arivera12** [comment] 2020-10-02 00:04
@Eilon 

When this gonna be added?

The changes are minimal but it will have a huge impact on this project cause it should make all blazor apps and libs already portable to Mobile Blazor Bindings.

I am anxious for the next release with these changes to see some current projects I already have developed running on top of this!

**Comment by AmirImam** [comment] 2020-10-04 05:52
@arivera12 
What did you do to make it work?
still not working for me
I realized that IJSRuntime not registered in **Microsoft.MobileBlazorBindings.WebView.BlazorHybridServiceCollectionExtensions**, so I added it like that
`services.AddScoped<IJSRuntime, BlazorHybridJSRuntime>();`
but didn't work too

**Comment by arivera12** [comment] 2020-10-04 13:27
@AmirImam I downloaded the source code and edit it with these changes https://github.com/soags/MobileBlazorBindings/commit/7abd02fe816869daee9f3915c2923c8b4199e18e

**Comment by AmirImam** [comment] 2020-10-05 10:36
@arivera12 
Thank you, it worked now

**Comment by Eilon** [comment] 2020-10-05 16:27
Sorry I was away from work last week but I'm back now. I'll review the change and see if it is safe to merge, hopefully this week!

**Comment by Eilon** [comment] 2020-10-05 16:27
Oh, and thank you so much @arivera12 for trying it out and confirming that it works, that is hugely helpful!

**Comment by arivera12** [comment] 2020-10-05 20:38
@AmirImam which platforms did you the IJSRuntime? can you provide your feedback?

**Comment by 199621616** [comment] 2020-10-06 02:56
It's in 0.5-preview, great.

**Comment by AmirImam** [comment] 2020-10-06 04:53
@arivera12 
I just tested it on android & windows. It worked on android perfectly but didn't work on windows, just blank page. I tried to catch all exceptions following these changes #171 but still blank page

**Comment by arivera12** [comment] 2020-10-06 05:08
@AmirImam 
I mentioned that over here https://github.com/xamarin/MobileBlazorBindings/issues/150#issuecomment-702345286

**Comment by Eilon** [comment] 2020-10-06 22:55
OK well I can confirm that the same change works for me on Android, iOS, and Windows. I'll try Mac later but I'd assume it works there all the same because none of this is particularly platform-specific.

I'll see if I can massage the code a bit because it seems that some aspects of the service management that already existed is a bit spaghetti-ish.

Expect a PR for this soon!

**Comment by Eilon** [comment] 2020-10-06 23:28
One problem that I think exists with this implementation is that I'm not sure it works well when there is more than one BlazorWebView in the app. Multiple BlazorWebView instances will end up sharing some references when I think they should each have their own, such as the proxied `BlazorHybridJSRuntime`. I'll have to think about this some more about how to keep each `BlazorWebView` sufficiently separated.

**Comment by arivera12** [comment] 2020-10-07 00:47
I think about this last night. What about if we have multiple BlazorWebView's instance on the same or separate windows? We would need to make IJSRuntime run on BlazorWebView scope instead of globally (singleton) scoped.

**Comment by arivera12** [comment] 2020-10-07 00:48
But let's think about use of case, it would be possible to have a case that we need 2 or more BlazorWebView on the same window?

**Comment by arivera12** [comment] 2020-10-07 00:59
But yes if we could have proxied service for each BlazorWebView it would be awesome, it will give the ability to have multiple WebUI on a same app.

**Comment by Eilon** [comment] 2020-10-07 03:55
Definitely possible to have more than one BlazorWebView, such as in this example: https://github.com/xamarin/MobileBlazorBindings/tree/master/samples/HybridMessageApp/HybridMessageApp

In this fake e-mail app there is one for the "folder list" and one for the "email list" that also hosts the "email content".

I'm hoping it'll be fairly straight-forward to get this implemented. I think I have it sketched out in Notepad and now I need to translate it into code.

**Comment by Eilon** [comment] 2020-10-07 21:02
Hi everyone, I have a PR for a fix for this issue here: https://github.com/xamarin/MobileBlazorBindings/pull/195

I want to get some extra eyes on the PR before I merge it. If it's all good, we'll get this in for the next preview, or in the meantime once it's merged we'll have a nightly build that you can use.

**Closed** 2020-10-14 20:31 UTC
Labels: area-mobileblazorbindings, enhancement, hybrid-apps

**Comment by Eilon** [comment] 2020-10-14 20:37
Thank you everyone for suggesting this change (it's a good one!) and working with me on getting the right fix in! @soags @arivera12 @SteveSandersonMS

**Comment by Eilon** [comment] 2020-10-14 22:49
The build has completed and you can try it out from the NuGet feed described here: https://docs.microsoft.com/mobile-blazor-bindings/contribute/nightly-builds
