### ISSUE TITLE
Mobile blazor cannot use third-party blazor components

### ISSUE THREAD

**Issue by hw72869951** [xamarin/MobileBlazorBindings#160] opened 2020-08-02 15:41 UTC

**Comment by yuhongw** [comment] 2020-08-03 01:46
Probably caused by JSRuntime. Please see #150 IJSRuntime injection as web-specific service and this [commit ](https://github.com/soags/MobileBlazorBindings/commit/7abd02fe816869daee9f3915c2923c8b4199e18e)

**Comment by Eilon** [comment] 2020-08-03 16:58
Original title: `Mobile blazor无法使用第三方blazor组件`
Translated title: `Mobile blazor cannot use third-party blazor components`

**Comment by arivera12** [comment] 2020-10-05 20:40
This is related to https://github.com/xamarin/MobileBlazorBindings/issues/150

**Comment by Eilon** [comment] 2020-10-05 21:25
@arivera12 yes this seems likely. Without further info in this issue I think that's the assumption I will make, so I'm closing this issue. Thank you again for your assistance with these issues!

**Closed by Eilon** 2020-10-05 21:25 UTC
