### ISSUE TITLE
Editor error when Frame is nested inside Frame

### ISSUE THREAD

**Issue by Dreamescaper** [xamarin/MobileBlazorBindings#213] opened 2020-11-01 23:09 UTC
That seems like a tooling error, but I'm not sure where would be better to log it.

Editor is not able to match start/end tags for Frame element when one Frame is nested inside another Frame.
That breaks syntax highlighting and auto-format is broken.

Example:
```
<ContentPage>
    <Frame>
        <StackLayout>
            <Frame></Frame>
        </StackLayout>
    </Frame>
</ContentPage>
```

![AtUhZ4rq3r](https://user-images.githubusercontent.com/17177729/97817907-eca0a800-1ca7-11eb-899f-291db97e8429.gif)

**Comment by Eilon** [comment] 2020-11-02 05:46
Hmm well that's weird! I've never seen this error so I'll investigate.

**Comment by Eilon** [comment] 2020-11-02 05:47
I can reproduce this on my machine as well. I can't believe I've never seen this, so weird!

**Comment by Eilon** [comment] 2020-11-02 05:48
Even this totally trivial case causes the warning:

```xml
<Frame>
<Frame>

</Frame>
</Frame>
```

I wonder if this conflicts with some built-in Blazor/Razor thing? I'll investigate some more tomorrow and maybe consult with the Razor Editor experts.

**Comment by Eilon** [comment] 2020-11-02 18:44
I feel like maybe `Frame` is conflicting with some other kind of Blazor thing. If you use the full type name there's no warning:

```xml
<Microsoft.MobileBlazorBindings.Elements.Frame BorderColor="Color.Orange">
    <Microsoft.MobileBlazorBindings.Elements.Frame BorderColor="Color.Red">
    </Microsoft.MobileBlazorBindings.Elements.Frame>
</Microsoft.MobileBlazorBindings.Elements.Frame>
```

And other tags all seem fine. It seems like just this one `<Frame>` tag is not happy.

**Comment by Eilon** [comment] 2020-11-02 18:54
Indeed, this doesn't work in a Blazor Web app either! Create a file called `Frame.razor` so that you have a `Frame` component and you get the exact same warning:

![image](https://user-images.githubusercontent.com/202643/97907191-bdb32200-1cf9-11eb-9b2b-eb8492439930.png)

**Comment by Eilon** [comment] 2020-11-02 19:12
And BTW this is only a design-time warning. It compiles and runs perfectly fine.

**Comment by Eilon** [comment] 2020-11-02 19:33
I logged a bug in the ASP.NET Core repo for Razor Tooling because this repros outside of a Mobile Blazor Bindings project: https://github.com/dotnet/aspnetcore/issues/27450

I'm closing this issue because there's presumably no action needed here.

Thank you for the bug report, this one was a weird one!

**Closed by Eilon** 2020-11-02 19:33 UTC
